services:
  # used for testing the docker file
  # uncomment to test
  # app:
  #   image: crm-system
  #   ports:
  #     - '4200:4200'
  #   env_file:
  #     - .env.staging
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      TZ: 'UTC'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
