services:
  # used for testing the docker file
  # uncomment to test
  # app:
  #   image: crm-system
  #   ports:
  #     - '4200:4200'
  #   env_file:
  #     - .env.staging
  db:
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      TZ: 'UTC'
    build:
      dockerfile: Dockerfile.db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
